sudo: false
language: node_js
before_install:
  - npm install -g npm@6.4.0
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '9'
  - '10'
  - 'stable'
script:
  - npm start validate
after_success:
  - npx codecov
branches:
  only:
    - master